name: Product images

on:
  push:
    tags:

jobs:
  reject_illegal_tags:
    name: Check if tag adheres to format 'productx.y.z-stackablea.b.c'
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Check if [${TAG_NAME}] matches expected format
        run: ./check_tag.sh $TAG_NAME

  parse_tag:
    name: Extract product, version and imageversion from tag name
    runs-on: ubuntu-latest
    needs:
      - reject_illegal_tags
    outputs:
      product: ${{ steps.extractproduct.outputs.product }}
      version: ${{ steps.extractversion.outputs.version }}
      image_version: ${{ steps.extractimageversion.outputs.imageversion }}
    steps:
      - id: extractproduct
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |
      - id: extractversion
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |
      - id: extractimageversion
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - parse_tag
    env:
      PRODUCT: ${{ needs.parse_tag.outputs.product }}
      PRODUCTVERSION: ${{ needs.parse_tag.outputs.version }}
      IMAGEVERSION: ${{ needs.parse_tag.outputs.imageversion }}
    steps:
      - name: Build image
        run: echo 'Building ${PRODUCT}${VERSION}-${IMAGEVERSION}'
