name: Product images

on:
  push:
    tags:
      - '*'

env:
  TAG_REGEX: iaeaie

jobs:
  reject_illegal_tags:
    name: Check if tag adheres to format 'productx.y.z-stackablea.b.c'
    runs-on: ubuntu-latest
    steps:
      - name: Get version tag
        id: version_tag
        run: |
          [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit 255
          TAG=${GITHUB_REF#refs/tags/}
          echo "Found tag: [$TAG]"
          echo "::set-output name=tag_name::$TAG"
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Check if tag matches expected format
        env:
          TAGNAME: ${{ steps.version_tag.outputs.tag_name }}
        run: |
          echo Checking $TAGNAME
          [[ "$TAGNAME" =~ ^kafka|zookeeper|nifi|druid|opa|hbase|hdfs|trino|airflow|superset|spark-k8s|.+-stackable\d+\.\d+\.\d+ ]] && echo "${TAGNAME}" valid || exit 255

  parse_tag:
    name: Extract product, version and imageversion from tag name
    runs-on: ubuntu-latest
    needs:
      - reject_illegal_tags
    env:
      TAGNAME: ${{ needs.reject_illegal_tags.outputs.tag_name }}
    outputs:
      product: ${{ steps.extractproduct.outputs.product }}
      version: ${{ steps.extractversion.outputs.version }}
      image_version: ${{ steps.extractimageversion.outputs.imageversion }}
    steps:
      - id: debug
        run: echo $TAGNAME
      - id: extractproduct
        run: |
          PRODUCT=$(echo $TAGNAME | \
          sed -r "s/(kafka|zookeeper|nifi|druid|opa|hbase|hdfs|trino|airflow|superset|spark-k8s).*/\1/" \
          )
          echo "Extracted [\"$PRODUCT\"] as product"
          echo "::set-output name=product::$PRODUCT"
      - id: extractversion
        run: |
          VERSION=$(echo $TAGNAME | \
          sed -r "s/(kafka|zookeeper|nifi|druid|opa|hbase|hdfs|trino|airflow|superset|spark-k8s)//" | \
          sed -r "s/([^-]+)-.*/\1/" \
          )
          echo "Extracted [\"$VERSION\"] as version"
          echo "::set-output name=version::$VERSION"
      - id: extractimageversion
        run: |
          IMAGEVERSION=$(echo $TAGNAME | \
          sed -r "s/(kafka|zookeeper|nifi|druid|opa|hbase|hdfs|trino|airflow|superset|spark-k8s)//" | \
          sed -r "s/^[^-]+-stackable(.*)/\1/" \
          )
          echo "Extracted [\"$IMAGEVERSION\"] as imageversion"
          echo "::set-output name=imageversion::$IMAGEVERSION"

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - parse_tag
    env:
      PRODUCT: ${{ needs.parse_tag.outputs.product }}
      PRODUCTVERSION: ${{ needs.parse_tag.outputs.version }}
      IMAGEVERSION: ${{ needs.parse_tag.outputs.imageversion }}
    steps:
      - name: Build image
        run: echo "Building ${PRODUCT}${VERSION}-${IMAGEVERSION}"