name: Product images

on:
  push:
    tags:

jobs:
  reject_illegal_tags:
    name: Check if tag adheres to format 'productx.y.z-stackablea.b.c'
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
    steps:
      run: [[ "$TAG_NAME" =~ ^kafka|zookeeper|nifi|druid|opa|hbase|hdfs|trino|airflow|superset|spark-k8s|.+-stackable\d+\.\d+\.\d+ ]] && echo "Tag valid"  || exit -1
        
  parse_tag:
    name: Extract product, version and imageversion from tag name
    runs-on: ubuntu-latest
    needs:
      - reject_illegal_tags
    outputs:
      product: ${{ steps.extractproduct.outputs.product }}
      version: ${{ steps.extractversion.outputs.version }}
      image_version: ${{ steps.extractimageversion.outputs.imageversion }}
    steps:
      - id: extractproduct
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |
      - id: extractversion
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |
      - id: extractimageversion
        env:
          TRIGGER: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
        run: |

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs:
      - parse_tag
    env:
      PRODUCT: ${{ needs.parse_tag.outputs.product }}
      PRODUCTVERSION: ${{ needs.parse_tag.outputs.version }}
      IMAGEVERSION: ${{ needs.parse_tag.outputs.imageversion }}
    steps:
      run: echo 'Building ${PRODUCT}${VERSION}-${IMAGEVERSION}'
